# Generated by Django 5.0.6 on 2024-07-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_remove_customuser_email_remove_customuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
