# Generated by Django 5.0.6 on 2024-07-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_parkingspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='hourlyrate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_spots', to='parking.customuser'),
        ),
    ]
