# Generated by Django 5.0.6 on 2024-07-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_customuser_balance_parkingsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='balance',
            new_name='credit',
        ),
    ]
